name: Build and Test

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
      - 'feature/*'  # Trigger the workflow on pushes to feature branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Run tests
      run: npm test
